# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Hello ctrex from your C++ friends :).
#'
#' @name
#' hello_ctrex_from_Cpp
#'
#' @description
#' This function returns a greeting message.
#'
#' @return
#' A string with "Hello, ctrex!".
#'
#' @export
NULL

hello_ctrex_from_Cpp <- function() {
    .Call(`_CTrex_hello_ctrex_from_Cpp`)
}

